const dialog=document.querySelector('#game-dialog');const panels=[...document.querySelectorAll('.game-panel')];let activeGame='';
const titleMap={snake:['GAME 01','Snake'],'2048':['GAME 02','2048'],orbit:['GAME 03','Orbit']};
function openGame(name){activeGame=name;panels.forEach(p=>p.classList.toggle('active',p.id===`${name}-panel`));document.querySelector('#game-kicker').textContent=titleMap[name][0];document.querySelector('#game-title').textContent=titleMap[name][1];if(!dialog.open)dialog.showModal();if(name==='2048'&&!tileBoard.some(Boolean))new2048();}
document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openGame(b.dataset.open)));document.querySelector('#close-game').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('close',()=>{stopSnake();stopOrbit();resetStartMessages();activeGame=''});

function resetStartMessages(){const snakeMessage=document.querySelector('#snake-message');snakeMessage.querySelector('strong').textContent='Snake';snakeMessage.querySelector('span').textContent='방향키 또는 WASD로 이동';snakeMessage.querySelector('button').textContent='Start';snakeMessage.classList.remove('hidden');const orbitMessage=document.querySelector('#orbit-message');orbitMessage.querySelector('strong').textContent='Orbit';orbitMessage.querySelector('span').textContent='좌우 키로 궤도를 회전해 충돌을 피하세요';orbitMessage.querySelector('button').textContent='Launch';orbitMessage.classList.remove('hidden')}

const snakeCanvas=document.querySelector('#snake-canvas'),sctx=snakeCanvas.getContext('2d');let snake=[],food={},snakeDir={x:1,y:0},nextDir={x:1,y:0},snakeTimer=null,snakeScore=0;const snakeBest=document.querySelector('#snake-best');snakeBest.textContent=localStorage.getItem('playroom-snake-best')||0;
function randomFood(){do{food={x:Math.floor(Math.random()*20),y:Math.floor(Math.random()*20)}}while(snake.some(p=>p.x===food.x&&p.y===food.y))}
function drawSnake(){const s=26;sctx.clearRect(0,0,520,520);sctx.fillStyle='#080b0d';sctx.fillRect(0,0,520,520);sctx.strokeStyle='rgba(70,255,166,.055)';sctx.lineWidth=1;for(let i=1;i<20;i++){sctx.beginPath();sctx.moveTo(i*s,0);sctx.lineTo(i*s,520);sctx.stroke();sctx.beginPath();sctx.moveTo(0,i*s);sctx.lineTo(520,i*s);sctx.stroke()}sctx.shadowColor='#fff';sctx.shadowBlur=18;sctx.fillStyle='#fff';sctx.beginPath();sctx.arc(food.x*s+13,food.y*s+13,6,0,Math.PI*2);sctx.fill();snake.forEach((p,i)=>{sctx.shadowColor='#55ffab';sctx.shadowBlur=i===0?22:12;sctx.fillStyle=i===0?'#c8ffe0':'#5affad';roundRect(sctx,p.x*s+3,p.y*s+3,20,20,7);sctx.fill()});sctx.shadowBlur=0}
function roundRect(c,x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r)}
function startSnake(){stopSnake();snake=[{x:8,y:10},{x:7,y:10},{x:6,y:10}];snakeDir=nextDir={x:1,y:0};snakeScore=0;document.querySelector('#snake-score').textContent=0;randomFood();drawSnake();document.querySelector('#snake-message').classList.add('hidden');snakeTimer=setInterval(tickSnake,105)}
function stopSnake(){clearInterval(snakeTimer);snakeTimer=null}
function tickSnake(){snakeDir=nextDir;const h={x:snake[0].x+snakeDir.x,y:snake[0].y+snakeDir.y};if(h.x<0||h.x>=20||h.y<0||h.y>=20||snake.some(p=>p.x===h.x&&p.y===h.y)){endSnake();return}snake.unshift(h);if(h.x===food.x&&h.y===food.y){snakeScore+=10;document.querySelector('#snake-score').textContent=snakeScore;randomFood()}else snake.pop();drawSnake()}
function endSnake(){stopSnake();const best=Math.max(Number(snakeBest.textContent),snakeScore);snakeBest.textContent=best;localStorage.setItem('playroom-snake-best',best);const m=document.querySelector('#snake-message');m.querySelector('strong').textContent='Game over';m.querySelector('span').textContent=`점수 ${snakeScore} · 다시 도전해보세요`;m.querySelector('button').textContent='Retry';m.classList.remove('hidden')}
function setSnakeDir(x,y){if(!snakeTimer)return;if(x!==-snakeDir.x||y!==-snakeDir.y)nextDir={x,y}}
document.querySelector('[data-action="snake-start"]').onclick=startSnake;document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>{const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[b.dataset.dir];setSnakeDir(...d)});

let tileBoard=Array(16).fill(0),tileScore=0,touchStart=null;const tileBest=document.querySelector('#tile-best');tileBest.textContent=localStorage.getItem('playroom-2048-best')||0;
function addTile(){const empty=tileBoard.map((v,i)=>v?null:i).filter(v=>v!==null);if(!empty.length)return;tileBoard[empty[Math.floor(Math.random()*empty.length)]]=Math.random()<.9?2:4}
function new2048(){tileBoard=Array(16).fill(0);tileScore=0;addTile();addTile();render2048()}
function render2048(){const board=document.querySelector('#board-2048');board.innerHTML='';tileBoard.forEach(v=>{const el=document.createElement('div');el.className='tile';if(v){el.textContent=v;el.dataset.value=v}board.appendChild(el)});document.querySelector('#tile-score').textContent=tileScore;const best=Math.max(Number(tileBest.textContent),tileScore);tileBest.textContent=best;localStorage.setItem('playroom-2048-best',best)}
function collapse(line){const vals=line.filter(Boolean),out=[];for(let i=0;i<vals.length;i++){if(vals[i]===vals[i+1]){out.push(vals[i]*2);tileScore+=vals[i]*2;i++}else out.push(vals[i])}while(out.length<4)out.push(0);return out}
function move2048(dir){const old=tileBoard.join(',');let next=Array(16).fill(0);for(let n=0;n<4;n++){let line=[];for(let k=0;k<4;k++){let r,c;if(dir==='left'){r=n;c=k}else if(dir==='right'){r=n;c=3-k}else if(dir==='up'){r=k;c=n}else{r=3-k;c=n}line.push(tileBoard[r*4+c])}line=collapse(line);for(let k=0;k<4;k++){let r,c;if(dir==='left'){r=n;c=k}else if(dir==='right'){r=n;c=3-k}else if(dir==='up'){r=k;c=n}else{r=3-k;c=n}next[r*4+c]=line[k]}}tileBoard=next;if(tileBoard.join(',')!==old){addTile();render2048();if(!canMove2048())setTimeout(()=>alert('더 움직일 수 없어요. New game으로 다시 시작하세요.'),80)}}
function canMove2048(){if(tileBoard.includes(0))return true;for(let r=0;r<4;r++)for(let c=0;c<4;c++){const v=tileBoard[r*4+c];if(c<3&&v===tileBoard[r*4+c+1]||r<3&&v===tileBoard[(r+1)*4+c])return true}return false}
document.querySelector('[data-action="2048-new"]').onclick=new2048;const boardEl=document.querySelector('#board-2048');boardEl.addEventListener('pointerdown',e=>touchStart=[e.clientX,e.clientY]);boardEl.addEventListener('pointerup',e=>{if(!touchStart)return;const dx=e.clientX-touchStart[0],dy=e.clientY-touchStart[1];if(Math.max(Math.abs(dx),Math.abs(dy))>24)move2048(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up');touchStart=null});

const orbitCanvas=document.querySelector('#orbit-canvas'),octx=orbitCanvas.getContext('2d');let orbitRunning=false,orbitFrame=0,orbitLast=0,orbitAngle=-Math.PI/2,orbitInput=0,obstacles=[],particles=[],orbitScore=0,orbitSpawn=0;const orbitBest=document.querySelector('#orbit-best');orbitBest.textContent=localStorage.getItem('playroom-orbit-best')||0;
function startOrbit(){stopOrbit();orbitRunning=true;orbitAngle=-Math.PI/2;obstacles=[];particles=[];orbitScore=0;orbitSpawn=0;document.querySelector('#orbit-score').textContent=0;document.querySelector('#orbit-message').classList.add('hidden');orbitLast=performance.now();orbitFrame=requestAnimationFrame(loopOrbit)}
function stopOrbit(){orbitRunning=false;cancelAnimationFrame(orbitFrame);orbitInput=0}
function loopOrbit(now){if(!orbitRunning)return;const dt=Math.min((now-orbitLast)/1000,.035);orbitLast=now;orbitAngle+=orbitInput*2.7*dt;orbitSpawn-=dt;if(orbitSpawn<=0){obstacles.push({a:Math.random()*Math.PI*2,r:390,size:10+Math.random()*10,type:Math.random()<.22?'energy':'danger'});orbitSpawn=Math.max(.38,1.05-orbitScore/900)}obstacles.forEach(o=>o.r-=145*dt);for(const o of obstacles){const diff=Math.abs(Math.atan2(Math.sin(o.a-orbitAngle),Math.cos(o.a-orbitAngle)));if(o.r<138&&o.r>102&&diff<.13){if(o.type==='danger'){endOrbit();return}else{o.r=-1;orbitScore+=50}}}obstacles=obstacles.filter(o=>o.r>-20);orbitScore+=dt*10;document.querySelector('#orbit-score').textContent=Math.floor(orbitScore);drawOrbit(now);orbitFrame=requestAnimationFrame(loopOrbit)}
function drawOrbit(now=0){const w=720,h=520,cx=w/2,cy=h/2;octx.clearRect(0,0,w,h);const bg=octx.createRadialGradient(cx,cy,10,cx,cy,390);bg.addColorStop(0,'#101d43');bg.addColorStop(.35,'#080d19');bg.addColorStop(1,'#05070b');octx.fillStyle=bg;octx.fillRect(0,0,w,h);octx.strokeStyle='rgba(102,151,255,.16)';[65,120,180,245].forEach(r=>{octx.beginPath();octx.arc(cx,cy,r,0,Math.PI*2);octx.stroke()});const p=octx.createRadialGradient(cx-12,cy-14,4,cx,cy,54);p.addColorStop(0,'#d6e7ff');p.addColorStop(.22,'#65a1ff');p.addColorStop(1,'#071335');octx.shadowColor='#4b8bff';octx.shadowBlur=38;octx.fillStyle=p;octx.beginPath();octx.arc(cx,cy,43,0,Math.PI*2);octx.fill();octx.shadowBlur=0;obstacles.forEach(o=>{const x=cx+Math.cos(o.a)*o.r,y=cy+Math.sin(o.a)*o.r;octx.fillStyle=o.type==='energy'?'#fff1a8':'#ff5478';octx.shadowColor=octx.fillStyle;octx.shadowBlur=16;octx.beginPath();octx.arc(x,y,o.size,0,Math.PI*2);octx.fill()});const px=cx+Math.cos(orbitAngle)*120,py=cy+Math.sin(orbitAngle)*120;octx.fillStyle='#dcecff';octx.shadowColor='#5c9cff';octx.shadowBlur=26;octx.beginPath();octx.arc(px,py,11,0,Math.PI*2);octx.fill();octx.shadowBlur=0}
function endOrbit(){stopOrbit();const score=Math.floor(orbitScore),best=Math.max(Number(orbitBest.textContent),score);orbitBest.textContent=best;localStorage.setItem('playroom-orbit-best',best);const m=document.querySelector('#orbit-message');m.querySelector('strong').textContent='Signal lost';m.querySelector('span').textContent=`에너지 ${score} · 분홍 장애물을 피하세요`;m.querySelector('button').textContent='Relaunch';m.classList.remove('hidden')}
document.querySelector('[data-action="orbit-start"]').onclick=startOrbit;document.querySelectorAll('[data-orbit]').forEach(b=>{const v=b.dataset.orbit==='left'?-1:1;b.addEventListener('pointerdown',e=>{e.preventDefault();orbitInput=v});['pointerup','pointercancel','pointerleave'].forEach(n=>b.addEventListener(n,()=>orbitInput=0))});drawOrbit();

document.addEventListener('keydown',e=>{if(!dialog.open)return;const key=e.key.toLowerCase(),dirs={arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]};if(key in dirs){e.preventDefault();if(activeGame==='snake')setSnakeDir(...dirs[key]);if(activeGame==='2048')move2048({arrowup:'up',w:'up',arrowdown:'down',s:'down',arrowleft:'left',a:'left',arrowright:'right',d:'right'}[key]);if(activeGame==='orbit')orbitInput=dirs[key][0]}});document.addEventListener('keyup',e=>{if(activeGame==='orbit'&&['arrowleft','a','arrowright','d'].includes(e.key.toLowerCase()))orbitInput=0});

function registerWebMCP(){const mc=document.modelContext;if(!mc?.registerTool)return;const tool={name:'start_game',title:'게임 시작',description:'PLAYROOM에서 Snake, 2048, Orbit 중 하나를 열고 새 게임을 시작합니다.',inputSchema:{type:'object',properties:{game:{type:'string',enum:['snake','2048','orbit']}},required:['game'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute({game}){if(!titleMap[game])throw new Error('지원하지 않는 게임입니다.');openGame(game);if(game==='snake')startSnake();if(game==='2048')new2048();if(game==='orbit')startOrbit();return{game,status:'started'}}};try{Promise.resolve(mc.registerTool(tool)).catch(()=>{})}catch{}}
registerWebMCP();drawSnake();

